<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'stripe_official.ps_accounts_installer' shared service.

return $this->services['stripe_official.ps_accounts_installer'] = new \PrestaShop\PsAccountsInstaller\Installer\Installer('^7.0.9');
