<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'stripe_official.module' shared service.

return $this->services['stripe_official.module'] = \Module::getInstanceByName('stripe_official');
