<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\Module\PsAccounts\Controller\Admin\OAuth2Controller' shared service.

return $this->services['PrestaShop\\Module\\PsAccounts\\Controller\\Admin\\OAuth2Controller'] = new \PrestaShop\Module\PsAccounts\Controller\Admin\OAuth2Controller();
