<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGtv734y\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGtv734y/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerGtv734y.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerGtv734y\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerGtv734y\appDevDebugProjectContainer([
    'container.build_hash' => 'Gtv734y',
    'container.build_id' => 'e3a56ddb',
    'container.build_time' => 1752068301,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGtv734y');
