<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUqgyy7s\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUqgyy7s/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUqgyy7s.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUqgyy7s\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUqgyy7s\appDevDebugProjectContainer([
    'container.build_hash' => 'Uqgyy7s',
    'container.build_id' => '4b54a18f',
    'container.build_time' => 1751895409,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUqgyy7s');
