<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXvzf59c\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXvzf59c/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXvzf59c.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXvzf59c\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXvzf59c\appDevDebugProjectContainer([
    'container.build_hash' => 'Xvzf59c',
    'container.build_id' => 'bacdcc59',
    'container.build_time' => 1751888794,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXvzf59c');
